### ISSUE TITLE
[Feature Request] web links

### ISSUE THREAD

**Issue by FootPrintStudio** [jpoles1/obsidian-litegal#3]
Are there any plans to support web links? I like to keep my images for certain things online to save local space.

**Comment by jpoles1** [comment]
To clarify, it sounds like you want to be able to link in pictures using a URL like `http://website.com/image.jpg`, is that right?

**Comment by FootPrintStudio** [comment]
Yes, that is correct.

**Comment by jpoles1** [comment]
Web links should now work, as long as they include "http://" or "https://". Please update and it should be working for you! Let me know if any issues there!

**Comment by FootPrintStudio** [comment]
Seems to work just fine, I appreciate it.
